### PR TITLE
remove extra yml apb yml file

### PR DESCRIPTION
**Pull request by laurafitzgerald**
**What**
Looks like this is an extra file that's out of date. The syntax in other apbs is that the apb file is name `apb.yml` and there's already one of those in this repo.

ping @odra  as  you created this file cc @sedroche

### CODE REVIEW

**Comment by sedroche** [comment]
@laurafitzgerald It seems the file is for creating a service instance. It looks ok to me but I will leave @odra have the final say

**Comment by laurafitzgerald** [comment]
@sedroche yes I'll also have to defer to @odra here. This file is unique to the mobile client app apbs (i.e. only xamarin has it) so wasn't sure what it's use is.

**Review by odra — APPROVED** [review]

**Comment by laurafitzgerald** [comment]
hi @odra thanks for the approval. are there other files that are duplicated like this one. From the original change it seemed there a few added. Or is it enough to just remove this one to remove the confusion with the apb file?

**Comment by odra** [comment]
Just this one, I created it in order to test the apb itself and forgot to remove it.

**Comment by laurafitzgerald** [comment]
@odra thanks for the feedback - merged :)

**Pull request merged**
